AC_INIT(#PROJECTNAME,#PROJECTVERSION)
AC_CONFIG_AUX_DIR(config)
AM_INIT_AUTOMAKE
AC_PREFIX_DEFAULT(`pwd`)
AC_PROG_CXX
AC_HEADER_STDC
AC_LANG_CPLUSPLUS
#AC_ENABLE_SHARED
AC_PROG_LIBTOOL

PKG_CHECK_MODULES(SCHDEPS,libccgnu2)

CPPFLAGS="${CPPFLAGS} ${SCHDEPS_CFLAGS}"
CXXFLAGS="${CXXFLAGS} ${SCHDEPS_CFLAGS}"

if test $JDE_PATH
then
  CPPFLAGS="${CPPFLAGS} -I$JDE_PATH/include"
  CXXFLAGS="${CXXFLAGS} -I$JDE_PATH/include"
  PATH="$JDE_PATH/bin:$PATH"
fi

AC_CHECK_HEADER([jde+.h],,AC_MSG_ERROR([jde+.h header not found. Install jde+ or define JDE_PATH]))
AC_PATH_PROG(JXMLC,jxmlc,jxmlc)
AC_SUBST(JXMLC)

AC_OUTPUT([
Makefile
])
