#!/bin/bash
gcc -g -Wall -c `pkg-config --cflags gmodule-2.0 libglade-2.0` schema_export1.c
gcc -g -Wall `pkg-config --libs gmodule-2.0 libglade-2.0` -shared -o schema_export1.jde schema_export1.o

gcc -g -Wall -c `pkg-config --cflags gmodule-2.0 libglade-2.0` schema_export2.c
gcc -g -Wall `pkg-config --libs gmodule-2.0 libglade-2.0` -shared -o schema_export2.jde schema_export2.o